SSD/nand_flash_memory.h, SSD/nand_flash_memory_mock.h, SSD/nand_reader.cpp, SSD/nand_reader.h, SSD/nand_reader_test.cpp
패치 내용
- 
패치 세부 내용 
1.  LBA 가 범위 밖일 때 exception이 나도록 구현했습니다.
2.  read type 을 int -> string으로 수정했습니다.
3.  test fixture 도입했습니다.
-
Check lists
=> Nand read 범위 밖의 LBA값 exception 처리 및 리턴 타입 string으로 수정

TestShell/TestShell.vcxproj, TestShell/TestShell.vcxproj.filters, TestShell/command.cpp, TestShell/command.h, TestShell/command_parser.cpp, TestShell/command_parser.h, TestShell/shell.cpp, TestShell/test_testshell_command_parser.cpp
패치 내용
Command class를 생성하였습니다. (Refac)
패치 세부 내용
1. Command class가 추가됨에 따라 이 객체를 사용하는 CommandParser, Shell 에서 함께 수정이 발생하였습니다
2. Command 는 Factory Pattern을 적용하여 User의 input command에 맞는 Command를 return하도록 구현했습니다.
3.
기존 vector<string> 으로 command 정보를 return 하던 것을 class 형태로 수정하였습니다.
Check lists
=> Test shell/command review

SSD/SSD.vcxproj, SSD/SSD.vcxproj.filters, SSD/main.cpp, SSD/ssd.cpp, SSD/ssd.h, SSD/ssd_test.cpp
패치 내용
- 
패치 세부 내용
1. SSD Run 으로 Read 할 수 있도록 구현했습니다.
2. FileHandler Mocking을 위해 SSD 는 main에서 FileHandler 를 생성자 주입받습니다.
3. SSD 내부에서 ArgumentParser 를 이용해 파싱후 명령어에 따라 Reader 나 Writer를 호출해 동작합니다.
-
Check lists
=> SSD Run 으로 Read 명령어 실행 구현

SSD/ArgumentParser.cpp, SSD/ArgumentParser.h, SSD/ArgumentParser_test.cpp, SSD/nand_flash_memory_impl.cpp, SSD/nand_flash_memory_impl_test.cpp, SSD/ssd.cpp, SSD/ssd_test.cpp
패치 내용
- 
패치 세부 내용
1. NandFlashMemoryImpl 의 write 기능 구현
2. SSD 에서 Write 명령어 구현
3. ArgParser 에서 getData 의 리턴타입을 string으로 변경
- 
Check lists
=> nand write impl 과 ssd 에서 write 호출하는 부분 구현

TestShell/command.cpp, TestShell/command.h, TestShell/test_with_mock.cpp
패치 내용
-  2_PartialLBAWrite 기능을 구현하였습니다.
패치 세부 내용
1.2_PartialLBAWrite TC 구현하였습니다.
일단은 Read/Write가 지정된 횟수만큼 다 수행하는 지를 확인하는 TC를 추가하였습니다.
2. 2_PartialLBAWrite 기능 enable 하였습니다.
3. 
-
```
30회 반복
4번 LBA에 값을 적는다.
0번 LBA에 같은 값을 적는다.
3번 LBA에 같은 값을 적는다.
1번 LBA에 같은 값을 적는다.
2번 LBA에 같은 값을 적는다.
LBA 0 ~ 4번 모두 같은지 확인
```
위 시나리오대로 수행이 되는 지 확인해주시면 될 것 같습니다.
해당 commit은  RED/GREEN에 해당되는 내용이어서 Refac은 추후에 하겠습니다.
Check lists
=> Test shell/2 script enable

SSD/ArgumentParser.cpp, SSD/global_config.h
패치 내용
- SSD argument parser에서 문자 비교 버그 수정
- char *argv[] 와 character를 비교하는 버그가 있었습니다. string으로 변환하여 비교 or strcmp() 를 사용해야 하는데, 
추후 cmd의 char가 1개 이상이 되는 경우를 대비하여 string type으로 변환하여 비교하도록 수정했습니다.
패치 세부 내용
1. character type을 string으로 변환하여 비교
2. 추후 명령어가 char 1개가 아닌 경우에 대비하여 string type 사용
3. 상수값은 GlobalConfig.h에 정의한 값으로 사용
- 문자열 비교에서 예외 사항이 있을 지 확인 부탁드립니다.
Check lists
=> SSD argument parser에서 문자 비교 버그 수정

SSD/FileHandler.cpp, SSD/FileHandler.h, SSD/OutputHandler.h, SSD/SSD.vcxproj, SSD/file_handler_mock.h, SSD/nand_flash_memory_impl_test.cpp, SSD/ssd.cpp
패치 내용
- ssd_nand.txt 초기 파일 생성
패치 세부 내용
1. NandFlashMemoryImplFixutre 도입
2. ssd_nand.txt 초기 파일 생성 TC 추가
3. ssd_nand.txt 초기 파일 생성부 구현
-
Check lists
=> ssd_nand.txt 초기 파일 생성

TestShell/TestShell.vcxproj, TestShell/TestShell.vcxproj.filters, TestShell/logger.cpp, TestShell/logger.h, TestShell/test_logger.cpp
패치 내용
- Logger 기능 추가
- Logger testcase 추가
패치 세부 내용
Logger
1. Logger는 프로그램 당 1개로 제한 (singleton으로 사용)
2. Multi threading 고려하지 않음 (lock 없음)
3. 요구사항대로, latest.log와 until______.log / until_____.zip을 생성함 (maxsize = 10K)
4. 사용법 아래 참고
Logger TC
1. Logger TC는 test용 log파일을 만들지 않습니다.
6. Log  backup파일을 계속 생산하는 TC는 Disable이 default입니다.
- Logger TC는 기본 logging test만 작동합니다. (10KB~30KB log는 Default disable)
- Logger 사용 방법은 아래와 같습니다.
``` 
#include "logger.h"
logger.print("function name", "message");
```
Check lists
=> Logger 기능 추가 PR

TestShell/TestShell.vcxproj, TestShell/test_command.cpp, TestShell/test_command_parser.cpp, TestShell/test_logger.cpp, TestShell/test_with_mock.cpp, TestShell/test_with_real_ssd.cpp
패치 내용
- 간간히 발생하던 linking 에러 수정
패치 세부 내용
1. header 가 compile 대상으로 넘어가있어 생겼던 것으로 추측합니다.
2. Test 코드들은 전부 Debug모드때만 빌드하도록 수정합니다.
3.
-
Check lists
=> 간간히 발생하던 linking 에러 수정

SSD/SSD.vcxproj, SSD/SSD.vcxproj.filters, SSD/erase_command.cpp, SSD/erase_command.h, SSD/read_command.cpp, SSD/read_command.h, SSD/ssd_command.cpp, SSD/ssd_command_test.cpp, SSD/write_command.cpp, SSD/write_command.h
패치 내용
- SSD argument 예외처리 추가 및 Unittest 추가
패치 세부 내용
1. read command address 에 문자가 들어오는 경우 예외 처리
2. write command data가 hex 값이 아닌 경우 예외 처리
3. write command data가 0xAAAABBBB 같은 0x 가 붙은 8자리 hexa digit이 아닌 경우 error 처리
4. unittest 추가
- 예외처리에서 빠진 부분이 있을 수 있는 지 확인 부탁드립니다.
Check lists
=> SSD argument 예외처리 추가 및 Unittest 추가

TestShell/TEST_SHELL_CONFIG.h, TestShell/erase_command.cpp, TestShell/erase_range_command.cpp, TestShell/exit_command.cpp, TestShell/full_read_command.cpp, TestShell/full_write_and_read_compare_command.cpp, TestShell/full_write_command.cpp, TestShell/help_command.cpp, TestShell/partial_LBA_write_command.cpp, TestShell/read_command.cpp, TestShell/write_command.cpp, TestShell/write_read_aging_command.cpp
패치 내용
- command 객체를 생성하기 전에 각 command factory 에서 argument size를 확인하도록 수정했습니다.
패치 세부 내용
1.
2.
3.
-
Check lists
=> Test shell/fix command arg size check

SSD/buffer_manager.cpp, SSD/buffer_manager.h, SSD/buffer_manager_test.cpp, SSD/global_config.h
패치 내용
- 
패치 세부 내용
1. 모든 buffer TC를 통과하도록 로직을 개선했습니다.
2. 내부적으로 lba 100개 각각에 대한 internal buffer 를 만들어 놓고 아래와 같이 수행합니다.
1. buffer file을 보고 internal Buffer를 업데이트 합니다.
2. write 나 erase 명령이 들어오면 internal Buffer를 업데이트합니다.
3. 2 이후에 internal Buffer를 보고 buffer file을 새로 작성합니다.
- 로직에 대한 디테일한 설명은 오프라인에서 설명 드리겠습니다.
Check lists
=> buffer 로직 개선

TestShell/ssd_impl.h
패치 내용
- SSD.exe를 찾는 환경추가
패치 세부 내용
1. VS 에서 실행 시, ../x64/Release/SSD.exe를 실행
2. 명령 프롬프트에서 바로 실행 시, 현재 디렉토리에서 SSD.exe 실행
-
Check lists
=> SSD.exe를 찾는 환경추가

TestShell/command.h, TestShell/command_parser.cpp, TestShell/full_write_and_read_compare_command.cpp, TestShell/main.cpp, TestShell/partial_LBA_write_command.cpp, TestShell/shell.cpp, TestShell/shell.h, TestShell/test_command_parser.cpp, TestShell/write_read_aging_command.cpp
패치 내용
- Shell 코드 간단한 리팩토링 하였습니다.
패치 세부 내용
1. Command 실행 실패 Exception 과 cmd parsing 실패 Exception 은 분리
2. 처리는 같습니다. 다만 Exception 만 일단 분리하였습니다.
3.
-
Check lists
=> [refac] Shell refactoring 및 Exception 분리

TestShell/erase_command.cpp, TestShell/erase_command.h, TestShell/erase_range_command.cpp, TestShell/erase_range_command.h, TestShell/exit_command.cpp, TestShell/exit_command.h, TestShell/full_read_command.cpp, TestShell/full_read_command.h, TestShell/full_write_and_read_compare_command.cpp, TestShell/full_write_and_read_compare_command.h, TestShell/full_write_command.cpp, TestShell/full_write_command.h, TestShell/help_command.cpp, TestShell/help_command.h, TestShell/partial_LBA_write_command.cpp, TestShell/partial_LBA_write_command.h, TestShell/read_command.cpp, TestShell/read_command.h, TestShell/write_command.cpp, TestShell/write_command.h, TestShell/write_read_aging_command.cpp, TestShell/write_read_aging_command.h
패치 내용
- 각 Command 객체는 factory를 통해서만 생성할 수 있도록 수정하였습니다.
패치 세부 내용
1. friend class XXXFactory; 를 사용하여서 각 factory에서 생성자 접근 가능하도록 수정
2. Factory::make_command()에서 new XXXCommand 를 통해 객체 생성
3.
- header file에선 모두 `생성자 private으로 옮기기` 수정만 하고 있습니다.
-  cpp file에선 factory 부분에서 `make_shared` 가 아닌 `shared_ptr`를 사용하여 객체 pointer를 반환합니다.
Check lists
=> [Refac] XXXCommand class의 객체는 각 Command의 factory에서만 하도록 수정하였습니다.

SSD/buffer_manager.cpp, SSD/buffer_manager_test.cpp
패치 내용
- 
패치 세부 내용
1.  erase file을 파싱할 때 write regex를 사용하여 발생한 버그 수정
-
Check lists
=> erase file을 파싱할 때 write regex를 사용하여 발생한 버그 수정

SSD/buffer_manager.cpp, SSD/buffer_manager_test.cpp
패치 내용
- 
패치 세부 내용
1. erase 와 인접한 write 가 erase 기준으로 count = 10 이거나 maxLBA 일때 erase buffer와 write buffer 를 파일로 입력하지 않는 버그를 수정합니다.
2.
3.
-
Check lists
=> [fix] maxLBA 값이 erase 영역과 걸친 write 이면 buffer에 기록이 안되는 이슈

SSD/buffer_manager.cpp
패치 내용
- Size 9 Erase에 대한 Buffer Logic 탈 경우, Size 10 Erase Cmd도 이어서 추가되는 버그 수정
패치 세부 내용
1. Buffer Logic에서 Buffer에 LBA 최대 또는 Erase Size 10개로 Erase Command를 버퍼에 쓸 경우, meetErase를 확인하는 조건 추가
-
Check lists
=> [Fix] Size 9 Erase에 대한 Buffer Logic 탈 경우, Size 10 Erase Cmd도 이어서 추가되는 버그 수정

TestShell/erase_command.cpp
패치 내용
- erase command 에서 99 를 invalid로 취급했던 것을 수정하였습니다.
패치 세부 내용
1.
2.
3.
-
Check lists
=> [FIX] erase range error

SSD/file_handler.h, SSD/file_handler_impl.cpp, SSD/file_handler_impl.h, SSD/file_handler_mock.h
패치 내용
- SSD compile 중 size_t 를 int로 형변환되어 발생한 warning 제거
- 
패치 세부 내용
1. 함수 parameter를 int --> size_t로 변경
-
Check lists
=> SSD compile 중 size_t 를 int로 형변환되어 발생한 warning 제거
