- SSD/SSD.vcxproj
- SSD/SSD.vcxproj.filters
- SSD/main.cpp
- TestShell/TestShell.vcxproj.filters
- TestShell/main.cpp
- [ERROR_FREE] SSD project.sln
패치 내용
- Debug, Release 분리
패치 세부 내용
1. Debug mode 빌드 시 Unit Test 돌아가게
2. Release mode 빌드 시 일반 실행 파일 생성되도록
3. 프로젝트에 테스트 파일 만들어두었습니다. 테스트 파일은 이쪽에 추가해주세요.
-
Check lists
> [Common] base code 수정

- TestShell/TestShell.vcxproj
- TestShell/TestShell.vcxproj.filters
- TestShell/storage.h
- TestShell/test_with_mock.cpp
패치 내용
- TestShell <-> SSD 에 대한 Mock 추가
패치 세부 내용
1. Mock 추가
-
Check lists
> TestShell <-> SSD 에 대한 Mock 추가

- SSD/SSD.vcxproj
- SSD/SSD.vcxproj.filters
- SSD/nand_flash_memory.h
- SSD/nand_flash_memory_mock.h
- SSD/nand_writer.cpp
- SSD/nand_writer.h
- SSD/nand_writer_test.cpp
패치 내용
- Write 기본 기능 구현
패치 세부 내용
1. LBA 0에 0 Write 하는 TC 통과하도록 구현
2. NandFlashMemory는 Mock 이용
Check lists
> Write 기본 기능 구현

- TestShell/test_with_mock.cpp
패치 내용
-  Mock을 활용한 Write Fail/Success test 입니다.
패치 세부 내용
1. 정해진 Index 범위를 넘어서 write 하는 경우
2. 정해진 Index 안으로 write 하는 경
3.
-
Check lists
> Test shell/write

- TestShell/TestShell.vcxproj
- TestShell/TestShell.vcxproj.filters
- TestShell/command_parser.cpp
- TestShell/command_parser.h
- TestShell/test_testshell_command_parser.cpp
패치 내용
-  
패치 세부 내용
1. Command Parser.cpp/ h를 구현을 하였습니다.
2. Command Parser 기본 Test Case를 구현하였습니다. ( read, write, exit, help, invalid command)
3.
- 지금은 RED/Green 단계이므로 기능 구현에만 중점적으로 확인해주시면 좋을 것 같습니다.
Check lists
> Test shell/command parser

- SSD/SSD.vcxproj
- SSD/SSD.vcxproj.filters
- SSD/main.cpp
- SSD/ssd.cpp
- SSD/ssd.h
패치 내용
- SSD 인스턴스 생성 부분 리팩토링
패치 세부 내용
1. 싱글톤 적용
2. 생성자/소멸자 작성
- 싱글톤 구현 부분
Check lists
> [Refactoring] SSD 생성 코드 리팩토링

- SSD/nand_flash_memory.h
- SSD/nand_flash_memory_impl.cpp
- SSD/nand_flash_memory_impl.h
- SSD/nand_flash_memory_mock.h
- SSD/nand_writer.cpp
- SSD/nand_writer.h
- SSD/nand_writer_test.cpp
패치 내용
- Writer 구현
패치 세부 내용
1. Writer TC 보강
2. NandFlashMemory는 매개변수로 받은 전체 데이터를 write만 하도록 변경
3. 전체 read 후 write 하도록 logic 변경
Check lists
> Writer 모듈 수정

- TestShell/command.cpp
- TestShell/command.h
- TestShell/shell.cpp
- TestShell/shell.h
- TestShell/test_with_mock.cpp
패치 내용
-  1_FullWriteAndReadCompare 수행하는 Run() 함수 구현 및 UT 추가
패치 세부 내용
1. 1_FullWriteAndReadCompare을 확인하는 UT 추가
2. 1_FullWriteAndReadCompare 수행
3. build error hot fix
- 해당 부분 clean code가 필요 한 상태 입니다.
Check lists
> Test shell/script

- .gitignore
- SSD/ArgumentParser.cpp
- SSD/ArgumentParser.h
- SSD/FileHandler.h
- SSD/OutputHandler.h
- SSD/OutputHandler_test.cpp
- SSD/SSD.vcxproj
- SSD/SSD.vcxproj.filters
- SSD/global_config.h
- SSD/nand_flash_memory_impl.h
- SSD/nand_reader.cpp
- SSD/nand_reader_test.cpp
- SSD/nand_writer.cpp
- SSD/nand_writer.h
- SSD/nand_writer_test.cpp
패치 내용
- SSD Refactoring
패치 세부 내용
1. "ssd_output.txt", "ssd_nand.txt" gitignore 추가
2. global_config.h 에서 상수 관리
3. LBA out of range 검사 과정을 Parser에서 한 번 수행 (기존 Reader/Writer 검사 제거)
Check lists
> SSD Refactoring

- TestShell/TestShell.vcxproj
- TestShell/TestShell.vcxproj.filters
- TestShell/test_with_mock.cpp
패치 내용
- Mock TC 추가 
패치 세부 내용
1. Command class내부 run 함수 test
2. Factory make method test
- Factory에서 command 생성하여, command->run 함수까지 수행하는 test
- Mock으로 read/write 호출 횟수 체크
Check lists
> Mock TC 추가 PR

- SSD/ssd_test.cpp
패치 내용
- 
패치 세부 내용
1. ssd test 에 중복코드 제거하였습니다.
2.
3.
-
Check lists
> ssd test에서 자주 사용하는 값 fixture 추가 및 magic number 삭제

- TestShell/command.cpp
- TestShell/command.h
- TestShell/test_with_mock.cpp
패치 내용
- read/write, full read/write 수정
패치 세부 내용
1.요구사항에 맞게 해당 기능 수행 시 로그 출력
2.1번을 만족하기 위해 printResult 매서드 추가
3.1,2번 확인을 위한 UT 수정
-
Check lists
> read/write, full read/write 수정

- TestShell/TestShell.vcxproj
- TestShell/TestShell.vcxproj.filters
- TestShell/ssd_impl.cpp
- TestShell/ssd_impl.h
- TestShell/ssd_interface.h
- TestShell/test_with_real_ssd.cpp
패치 내용
- SSD Impl 구현 및 ssd.exe 실행으로 수행하는 TC 추가했습니다.
패치 세부 내용
1. [RED] ssd impl을 수행하는 tc 추가
2. [GREEN] ssd impl 구현
3.
- 실제 ssd.exe를 수행하면서 tc prepare 단에 추가된  all erase가 있는데 그 부분 한번 확인해주세요~!
Check lists
> Test shell/create ssd impl

- SSD/SSD.vcxproj
- SSD/SSD.vcxproj.filters
- SSD/buffer_manager.cpp
- SSD/buffer_manager.h
- SSD/buffer_manager_test.cpp
- SSD/global_config.h
패치 내용
- 
패치 세부 내용
1. buffer read / write / erase / flush 구현.
2. 아직 file에 실제로 기록하진 않습니다.
3. 아직 통과하지 않는 TC는 DISABLED_ 를 붙여 추가했습니다.
- 
Check lists
> buffer manager 기본 로직 추가.

- TestShell/full_write_command.h
- TestShell/test_command.cpp
- TestShell/test_with_real_ssd.cpp
- TestShell/write_read_aging_command.cpp
- TestShell/write_read_aging_command.h
패치 내용
-  BuildFail 나던 부분 수정하였습니다. Commit 분리하여 Real SSD commit TC 수정부도 함께 review에 요청드립니다.
패치 세부 내용
1. include 누락 수정
2.
3.
-
Check lists
> Test shell/build fix

- .gitignore
- SSD/FileHandler.cpp
- SSD/FileHandler.h
- SSD/buffer_manager.cpp
- SSD/buffer_manager.h
- SSD/global_config.h
- SSD/ssd.cpp
- SSD/ssd.h
- SSD/ssd_test.cpp
패치 내용
- Buffer 디렉토리 & 파일 생성 동작
패치 세부 내용
1. Buffer Directory가 없을 경우 생성
2. Buffer File이 없을 경우 생성
-
Check lists
> [Feature] Buffer 디렉토리 & 파일 생성 동작

- SSD/FileHandler.cpp
- SSD/FileHandler.h
- SSD/FileHandler_test.cpp
- SSD/SSD.vcxproj
- SSD/SSD.vcxproj.filters
패치 내용
- 
패치 세부 내용
1. std에 이미 std::rename 이 있어 이를 호출하여 파일 명 변경하도록 구현했습니다.
2. 실제 동작 확인을 위해 FileHandler_test.h 에서 테스트 해보았습니다. DISABLED_ 붙여서 PR 올립니다.
-
Check lists
> [feat] fileHandler에 rename function 추가.

- TestShell/TEST_SHELL_CONFIG.h
- TestShell/full_write_and_read_compare_command.cpp
- TestShell/full_write_and_read_compare_command.h
- TestShell/test_command_parser.cpp
- TestShell/write_read_aging_command.cpp
- TestShell/write_read_aging_command.h
패치 내용
- 
패치 세부 내용
1. Custom Exception을 활용하여 테스트 도중 FAIL 발생 시 Test 중단하도록 수정
2. 매서드 추출을 통한  clean code
3.
-
Check lists
> [Refactor] 1_, 3_ testscript

- SSD/buffer_manager.cpp
- SSD/buffer_manager.h
- SSD/file_handler.cpp
- SSD/file_handler.h
- SSD/global_config.h
패치 내용
- Init 과정에서 저장되어 있는 Buffer File 기반으로 BufferManager의 버퍼 정보 업데이트
패치 세부 내용
1. Init 과정에서 저장되어 있는 Buffer File 기반으로 BufferManager의 버퍼 정보 업데이트
-
Check lists
> [feature] Init 과정에서 저장되어 있는 Buffer File 기반으로 BufferManager의 버퍼 정보 업데이트

- SSD/buffer_manager.cpp
- SSD/buffer_manager.h
- SSD/buffer_manager_test.cpp
- SSD/erase_command.cpp
- SSD/file_handler.cpp
- SSD/file_handler.h
- SSD/file_handler_mock.h
- SSD/global_config.h
- SSD/ssd.cpp
- SSD/ssd_test.cpp
- SSD/write_command_test.cpp
패치 내용
- Buffer Update 시 Buffer File 업데이트되도록 구현
패치 세부 내용
1.Buffer Update 시 Buffer File 업데이트되도록 구현
2. Buffer 기능 Enable 하였을 때 발생하는 추가 이슈들 Fix
-
Check lists
> [Feature] Buffer Update 시 Buffer File 업데이트되도록 구현

- TestShell/TEST_SHELL_CONFIG.h
- TestShell/TestShell.vcxproj
- TestShell/TestShell.vcxproj.filters
- TestShell/command.cpp
- TestShell/command.h
- TestShell/full_write_and_read_compare_command.cpp
- TestShell/full_write_and_read_compare_command.h
- TestShell/partial_LBA_write_command.cpp
- TestShell/partial_LBA_write_command.h
- TestShell/shell.cpp
- TestShell/shell.h
- TestShell/test_util.cpp
- TestShell/test_util.h
- TestShell/write_read_aging_command.cpp
- TestShell/write_read_aging_command.h
패치 내용
- 
패치 세부 내용
1. TestScript print를 각 script run에서 출력하도록 수정
2. 3_ script run() 코드 간결화
3. RandomGenerator Class 추가
4. 4_  script coomand 추가 및 UT 추가
-
Check lists
> [Refactor] TestScript print출력 이동 & 3_ script clean code

- TestShell/TEST_SHELL_CONFIG.h
- TestShell/erase_range_command.cpp
- TestShell/flush_command.cpp
- TestShell/full_write_command.cpp
- TestShell/read_command.cpp
- TestShell/ssd_impl.cpp
- TestShell/write_command.cpp
패치 내용
- ERROR 변수명 변경
패치 세부 내용
1. windows.h 에 pre-defined 변수임.
-
Check lists
> [fix] ERROR 변수명 변경

- TestShell/command.cpp
- TestShell/command.h
- TestShell/erase_command.cpp
- TestShell/erase_command.h
- TestShell/erase_range_command.cpp
- TestShell/erase_range_command.h
패치 내용
- Erase 관련  LBA erase 예외 확인 추가했습니다.
패치 세부 내용
1. Erase/EraseRange Command Class에서 범위 확인합니다.
2.
3.
-
Check lists
> Test shell/erase lba range check

- TestShell/TEST_SHELL_CONFIG.h
- TestShell/TestShell.vcxproj
- TestShell/TestShell.vcxproj.filters
- TestShell/command.cpp
- TestShell/command.h
- TestShell/command_factory_complex.h
- TestShell/command_list.h
- TestShell/erase_and_write_aging.h
- TestShell/erase_and_write_aging_command.cpp
- TestShell/full_write_and_read_compare_command.cpp
- TestShell/partial_LBA_write_command.cpp
- TestShell/shell_script.txt
- TestShell/test_with_mock.cpp
- TestShell/write_read_aging_command.cpp
- TestShell/write_read_aging_command.h
패치 내용
- 4_erase_and_write_aging 구현
패치 세부 내용
1. 4번 command를 확인 할 UT 작성
2. 4_erase_and_write_aging 구현
3. PASS출력 부분 method extract하여 commnad class 안으로 이동
4. 요구사항에 맞게 1번 Test 수정
-
Check lists
> [Feature] 4_erase_and_write_aging

- TestShell/command_runner.cpp
- TestShell/erase_and_write_aging_command.cpp
- TestShell/erase_command.cpp
- TestShell/erase_range_command.cpp
- TestShell/exit_command.cpp
- TestShell/flush_command.cpp
- TestShell/full_read_command.cpp
- TestShell/full_write_and_read_compare_command.cpp
- TestShell/full_write_command.cpp
- TestShell/help_command.cpp
- TestShell/logger.cpp
- TestShell/logger.h
- TestShell/partial_LBA_write_command.cpp
- TestShell/read_command.cpp
- TestShell/ssd_impl.cpp
- TestShell/test_logger.cpp
- TestShell/write_command.cpp
- TestShell/write_read_aging_command.cpp
패치 내용
- Command 에 Log를 추가했습니다.
패치 세부 내용
1.
2.
3.
-
Check lists
> [FEAT] Command 수행 Log 추가

- TestShell/test_with_real_ssd.cpp
패치 내용
- WRITE후 다시 READ하여 실제 원하는 DATA가 잘 써져 있는지 확인하는 TEST
패치 세부 내용
1.WRITE후 다시 READ하여 실제 원하는 DATA가 잘 써져 있는지 확인하는 TEST
2.
3.
-
Check lists
> [UT] Real READ/WRITE TEST

- TestShell/command.cpp
패치 내용
- 아주 간단합니다. 점 하나 추가했습니다!
패치 세부 내용
1.
2.
3.
-
Check lists
> [Fix] script 출력문 . 하나 누락 수정
